services:
  bagetter:
    image: bagetter/bagetter:1.0.4
    restart: on-failure
    environment:
      ApiKey: ${BAGETTER_API_KEY}
    ports:
      - "23001:8080"
    volumes:
      - bagetter-data:/data

volumes:
  bagetter-data:

