services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: Express
    ports:
      - "23000:1433"
    volumes:
      - db-data:/var/opt/mssql/data
      - db-log:/var/opt/mssql/log
      - db-secrets:/var/opt/mssql/secrets
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U sa -P ${MSSQL_SA_PASSWORD} -Q 'select 1'" ]
      interval: 5s
      timeout: 5s
      retries: 5

#  Doesn't work for some reason.
#  proget-db-init:
#    image: mcr.microsoft.com/mssql-tools:latest
#    command: ["/opt/mssql-tools/bin/sqlcmd", "-S db -U sa -P ${MSSQL_SA_PASSWORD} -Q 'CREATE DATABASE [ProGet] COLLATE SQL_Latin1_General_CP1_CI_AS'"]
#    depends_on:
#      db:
#        condition: service_healthy

  proget:
    image: proget.inedo.com/productimages/inedo/proget:23
    container_name: proget
    restart: unless-stopped
    environment:
      PROGET_SQL_CONNECTION_STRING: Data Source=db; Initial Catalog=ProGet; User ID=sa; Password=${MSSQL_SA_PASSWORD}
    ports:
      - "23001:80"
    volumes:
      - proget-packages:/var/proget/packages
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
  db-log:
  db-secrets:
  proget-packages:
