name: Build & test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Build project
      run: ./build.sh -Target All
      
    - name: Upload test results
      uses: actions/upload-artifact@v3.1.0
      if: ${{ always() }}
      with:
        name: test-results
        path: test-results
        if-no-files-found: error
        retention-days: 7

    - name: Upload packages
      uses: actions/upload-artifact@v3.1.0
      with:
        name: packages
        path: artifacts/*.nupkg
        if-no-files-found: error
        retention-days: 7
